# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: BUN Ci

permissions:
  contents: write

on:
  push:
    tags: 
      - "v*.*.*"

jobs:
  build-artifacts:
    name: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache 
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Dependencies
        run: bun install

      - name: Bun Build
        run: bun run wxt build

      # - name: Upload Build Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     include-hidden-files: true
      #     name: build-artifacts
      #     path: dist/

      - name: Confirm files
        run: ls dist

      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: dist/chrome-mv3/wxt.svg